"""empty message

Revision ID: 5b1875d86be2
Revises: a9be9b10430a
Create Date: 2023-02-07 10:07:52.890485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b1875d86be2'
down_revision = 'a9be9b10430a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_guests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contact_email', sa.String(length=120), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['contact_email'], ['contacts.email'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contact_email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_guests')
    # ### end Alembic commands ###
